
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test setup-stack
    steps:
    - name: Load it
      uses: tritonresearch/setup-stack@master
    - name: Observe it
      run: |
        echo $PATH
        stack update

